export const upcomingMatches = [
  {
    id: 1,
    homeTeam: "Arsenal",
    awayTeam: "Manchester City",
    date: "2024-03-31",
    time: "16:30",
    round: "Round 1",
    homeLogo: "/teams/arsenal.png",
    awayLogo: "/teams/mancity.png",
  },
  {
    id: 2,
    homeTeam: "Liverpool",
    awayTeam: "Brighton",
    date: "2024-03-31",
    time: "14:00",
    round: "Round 1",
    homeLogo: "/teams/liverpool.png",
    awayLogo: "/teams/brighton.png",
  },
  {
    id: 3,
    homeTeam: "Chelsea",
    awayTeam: "Manchester United",
    date: "2024-04-01",
    time: "20:00",
    round: "Round 2",
    homeLogo: "/teams/chelsea.png",
    awayLogo: "/teams/manutd.png",
  },
  {
    id: 4,
    homeTeam: "Tottenham",
    awayTeam: "Newcastle",
    date: "2024-04-02",
    time: "18:00",
    round: "Round 2",
    homeLogo: "/teams/tottenham.png",
    awayLogo: "/teams/newcastle.png",
  },
  {
    id: 5,
    homeTeam: "Leicester",
    awayTeam: "West Ham",
    date: "2024-04-03",
    time: "16:00",
    round: "Round 3",
    homeLogo: "/teams/leicester.png",
    awayLogo: "/teams/westham.png",
  },
];
